name: Generate design tokens

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Nome do arquivo de sa√≠da"
        required: true
        type: string
      tokens:
        description: "JSON dos tokens exportados do Figma"
        required: true
        type: string
      commitMessage:
        description: "Mensagem do commit"
        required: false
        type: string
        default: "Update design tokens"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create input JSON
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ github.event.inputs.filename }}
          json: ${{ github.event.inputs.tokens }}
          dir: 'input'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: ${{ github.event.inputs.commitMessage }}
          title: ${{ github.event.inputs.commitMessage }}
          body: "Design tokens have been updated via Figma and need to be reviewed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "main"